### ISSUE TITLE
Doesn't works on meteor 1.6 +

### ISSUE THREAD

**Issue by Oyshoboy** [scholtzm/meteor-accounts-steam#7]
Hi @scholtzm , tryied it today, nothing happends when I try to auth with steam.

**Comment by Oyshoboy** [comment]
```
Template.firstSlide.events({
    'click .loginWithSteam': function(event) {
    	var options = {
    		redirectUrl: 'https://example.com/done',
    		timeout: 10000
    	}
       Meteor.loginWithSteam(options);
    }
});
```
used this to initialize

**Comment by scholtzm** [comment]
I just tested this with Meteor v1.6.1 and it works fine for me: https://github.com/scholtzm/meteor-accounts-steam-example

**Comment by Oyshoboy** [comment]
@scholtzm  install an example, but it throws an error

```
/home/adman/.meteor/packages/meteor-tool/.1.6.1.1qpo8wv.inr2++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
						throw(ex);
						^

ReferenceError: ServiceConfiguration is not defined
    at Meteor.startup (meteor-accounts-steam-example/server/main.js:2:3)
    at Function.time (/home/adman/steamAuth/.meteor/local/build/programs/server/profile.js:309:28)
    at /home/adman/steamAuth/.meteor/local/build/programs/server/boot.js:427:13
    at /home/adman/steamAuth/.meteor/local/build/programs/server/boot.js:472:5
    at Function.run (/home/adman/steamAuth/.meteor/local/build/programs/server/profile.js:510:12)
    at /home/adman/steamAuth/.meteor/local/build/programs/server/boot.js:470:11
Exited with code: 1
Your application is crashing. Waiting for file change.
```

What does ServiceConfiguration means?

**Comment by Oyshoboy** [comment]
@scholtzm  how can I change redirectUrl and host? 
Cuz i have this one:
`Error in OAuth Server: redirectUrl (https://dve.mysite.me/) is not on the same host as the app (http://localhost:3000/)`

It's redirect me on locahost:3000

**Comment by Oyshoboy** [comment]
Done, set Root url on meteor! 
Thank you for help!
